language: cpp

compiler:
  - gcc

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install xorg-dev libglu1-mesa-dev
  - sudo apt-get install -qq libglfw-dev libglew-dev

before_script:
  - mkdir build
  - cd build
  - cmake ..

script: make